### PR TITLE
Decentralized approach

### LINKED ISSUE #2: How to handle dependencies that are only used in test?
I'm not sure how to handle `test/support/....` files.

In my `test/support` I sometimes add things to the same module structure for example:

lib/foo:
```elixir
module Foo do
end
```

test/support/factory.ex:
```elixir
module Foo.Factory do
end
```

Now Boundaries complains that `Foo.Factory` is not allowed from an other file in `test/support` (for example a helper file to setup some domain data).

Ideally I think I want to be able to say to ignore some files, or be able to change the boundaries for tests.

### LINKED ISSUE #3: deriving from `Jason.Encoder` requires you to add Jason as a boundary.
Opening for discussion. It's not really an issue, in that you have to add this line, but it's also not the cleanest.
Maybe someone has an idea about what to do with this?

### LINKED ISSUE #4: Crash: Protocol.UndefinedError
I just got a crash while defining the boundaries.
Something was wrong with my exports (I had none for some boundary. Adding exports solved the issue)

```bash
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:366: Enum.any?/2
    lib/boundaries/checker.ex:127: Boundaries.Checker.check_call/3
    (elixir) lib/stream.ex:569: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1583: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:3023: Enum.map/2
    (elixir) lib/enum.ex:2353: Enum.sort_by/3
    lib/boundaries/checker.ex:105: Boundaries.Checker.check_calls/3
    lib/boundaries.ex:32: Boundaries.check/3
    lib/mix/tasks/compile/boundaries.ex:198: Mix.Tasks.Compile.Boundaries.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:40: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```

### LINKED ISSUE #5: Proposal: boundaries redesign
Based on the [feedback gathered on Elixir Forum](https://elixirforum.com/t/boundaries-enforcing-boundaries-in-elixir-projects) and some issues reported here (#2 and #3), I'd like to propose the following changes to the library:

1. Move to a decentralized approach where each boundary is described in its root module.
2. Support unclassified modules

### Usage

Currently, boundaries are defined in a separate `boundaries.exs` file:

```elixir
[
  {MySystem, exports: [User]},
  {MySystemWeb, exports: [Endpoint], deps: [MySystem]}
]
```

In a decentralized approach, each boundary is defined in its root module:

```elixir
defmodule MySystem do
  use Boundary, exports: [User]

  # ...
end

defmodule MySystemWeb do
  use Boundary,
    exports: [Endpoint],
    deps: [MySystem]

  # ...
end
```

Note that with this approach, developers will sometimes need to add a module for the sole purpose of defining a boundary.

Internally, the injected code will be along the lines of:

```elixir
Module.register_attribute(__MODULE__, Boundary, persist: true)
Module.put_attribute(__MODULE__, Boundary, boundary_opts)
```

In particular, no function or macro will be injected into the caller module.

As a result, we lose a central place where one can inspect all the boundaries. However, based on the stored metadata, it's straightforward to add support for that via helper functions such as `Boundary.all/0` and possibly mix tasks which are implemented on top of those functions.

### Motivation

Personally, I think that placing a boundary specification close to its implementation makes more sense, and scales much better with respect to the project size. In a large codebase with many boundaries defined, managing a single large file might become much more difficult.

Another nice benefit is that a boundary name is now auto-inferred from the owner module, which means that if the module is renamed, the boundary name is automatically "synchronized".

Most importantly, a decentralized definition will make it possible to elegantly deal with the protocol implementation, which is a problem that is currently not handled properly.

Consider the following module:

```elixir
defmodule MySystem.SomeModule do
  defimpl Enumerable do
    # ...
  end
end
```

This code will generate the module `Enumerable.MySystem.SomeModule`, which is in a completely different namespace. In the current design, you need to introduce another boundary which follows the same rules as `MySystem.SomeModule`.

In theory, we could deduce that the impl module implements a protocol for `MySystem.SomeModule`, and automatically place the module into the same boundary as `MySystem.SomeModule`, but that decision is not always the right one.

Consider the following situation:

```elixir
# in the interface layer
defimpl SomeLib.Encoder, for: MySystem.SomeModule do ... end
```

In this case, the protocol implementation of the encoder is done for the purposes of the interface layer (i.e. `MySystemWeb`). Thus, in this case, the rules for the protocol implementation should not be the same as the rules for the domain module.

A decentralized approach can help us have an explicit interface to solve this situation:

```elixir
defmodule MySystem.SomeModule do
  defimpl Enumerable do
    # Make this module a part of the `MySystem` boundary
    use Boundary.ProtocolImpl, boundary: MySystem

    # Alternatively, if `boundary` is not specified, the impl belongs to the same
    # boundary as the implementation target (`MySystem.SomeModule`).
    use Boundary.ProtocolImpl
  end
end

# interface layer
defimpl SomeLib.Encoder do
  # Make this module a part of the `MySystemWeb` boundary
  use Boundary.ProtocolImpl, boundary: MySystemWeb
end
```

This feature would work only for modules which are implementing some protocol. Boundary membership of all other modules is determined from the module name, and can't be overridden.

If `use Boundary.ProtocolImpl` is not provided in a protocol impl, the module will be unclassified.

Finally, while not a top priority, a decentralized approach makes it possible to elegantly define internal boundaries (boundaries within boundaries):

```elixir
defmodule MySystem do
  use Boundary, ...
end

defmodule MySystem.Accounts do
  use Boundary, exports: [User, ...]
end

defmodule MySystem.Admin do
  use Boundary, deps: [Accounts, ...]
end
```

In this example, we define two internal boundaries in `MySystem`: `Accounts` and `Admin`, allowing function calls only from `Admin` into `Accounts`.

## Unclassified modules

Currently, all modules must included in some boundary. As it turns out, there are various scenarios where this requirement is too strict.

For example, introducing boundaries in a legacy project might require a large amount of work which can't be done in a single chunk. Thus, a team might instead decide to gradually introduce boundaries to the project. In such cases, we shouldn't report errors on unclassified modules. Omitting such warning would allow the team to detect violations for the currently established boundaries.

In addition, there is a problems of modules which are generated by some macro or the compiler. A simple example of this is using `@derive`. Consider the following code:

```elixir
defmodule MySystem.User do
  @derive Jason.Encoder
end
```

As a result of this, the module `Jason.Encoder.MySystem.User` will be created. This module shouldn't really be considered by boundaries at all, because the author doesn't have any control over the module implementation.

To tackle these problems, I propose the following solutions:

1. By default, we still emit warnings for unclassified modules.
2. An opt-out compiler switch is introduced (e.g. `--ignore-unclassified-modules`).
3. We support an ignore list, a configuration which allows devs to specify namespaces which should never be analyzed by boundaries (e.g. `Jason.Encoder`).

These properties should allow us to tackle all possible scenarios. A new project can start with the default behavior, using the ignore list to deal with `@derive` and other kinds of auto-generated modules. A legacy project can start with `--ignore-unclassified-modules` until they are able to completely cover the boundaries.

### PR DESCRIPTION
**Pull request by sasa1977**
Changes the library design, as outlined in #5:

- [X] [decentralized definitions of boundaries](https://github.com/sasa1977/boundaries/blob/ede277f536cc54e8204acc069f9511c0a2d2cf38/lib/boundary.ex#L41-L51)
- [X] [support for excluding some areas from boundary checks](https://github.com/sasa1977/boundaries/blob/ede277f536cc54e8204acc069f9511c0a2d2cf38/lib/boundary.ex#L158-L216)
- [X] [manual classification of protocol implementations](https://github.com/sasa1977/boundaries/blob/ede277f536cc54e8204acc069f9511c0a2d2cf38/lib/boundary.ex#L81-L111)

To try this version out, you need to depend on the version from the [decentralized-approach](https://github.com/sasa1977/boundaries/tree/decentralized-approach#boundary) branch. See readme in that branch for usage details.

Note that due to the changes, the OTP application is now called `:boundary`. If this PR gets merged, the GH repo will also be renamed.

resolves #5
resolves #4 
resolves #3 
resolves #2

### CODE REVIEW

**Comment by tomekowal** [comment]
Works OK in our project 👍 
I would still try to incorporate the flag `--ignore-unclassified-modules`. E.g. we are using `EctoEnum` library that that defines a couple of top-level modules.
It doesn't allow us to put `use Boundary, ignore?: true` inside them.

**Comment by sasa1977** [comment]
> Works OK in our project

Thank you for trying it out!

> I would still try to incorporate the flag `--ignore-unclassified-modules`. 

Adding that flag is easy enough. One problem is that you probably want to suppress the warnings only for a selected set of modules, not all of them. Luckily, in the new version, we expose [the function](https://github.com/sasa1977/boundaries/blob/decentralized-approach/lib/boundary.ex#L239-L246) which among other things returns a collection of non-classified modules. So people could use that function to make their own additional checks, without us needing to devise some pattern language for exclusion.

That said, I'd like to make an effort of deferring this feature as much as possible. So let's talk a little bit about your particular case.

> E.g. we are using `EctoEnum` library that defines a couple of top-level modules. It doesn't allow us to put `use Boundary, ignore?: true` inside them.

EctoEnum allows you to define enum modules inside other modules:

```elixir
defmodule MySystem.User do
  import EctoEnum
  defenum Role, ...
end
```

The module name in this case is `MySystem.User.Role`. In fact, this is how I prefer to do it myself (create enum inside the schema module). You might want to use some different namespacing scheme, but either way I think that putting `Role` & other enums at the top-level, next to `MySystem` and `MySystemWeb` is not the best approach.

In fact, I'd say that one reason for making boundaries is precisely to have a tool which helps us detect and correct such situations.

I guess that sooner or later we'll come across a library which unconditionally creates modules at the top-level. I guess at that point we'll need to support some ignore mechanism. However, I think that `EctoEnum` is an example where this is not required, as you can organize these modules inside your own namespaces, and thus you can include them in your boundaries. Does that make sense?

**Comment by tomekowal** [comment]
It makes perfect sense!
I just assumed that by „gradually introducing” the library to project you meant that:
- I add the dependency on boundary
- Ignore the modules I don’t know
- Focus on whatever part of the system I want with `use Boundary` and ignore other parts until I am done with this one

In my case adding EctoEnum’s to a namespace is the right solution.
The lib made me aware that I have one module that is called `MyApp.Web` while most are `MyAppWeb`, so it is another win.

I think that the main benefit of the lib is detecting the cross-boundary calls.
It might be a little bit discouraging for a new user to be forced to perform a heavy refactor before ripping the benefits.

Especially if he/she is only interested in cleaning some critical part of the app and not the entire project.

**Comment by sasa1977** [comment]
> I think that the main benefit of the lib is detecting the cross-boundary calls.

That's the main goal of the lib. I believe that requiring full coverage helps with that goal.

> It might be a little bit discouraging for a new user to be forced to perform a heavy refactor before ripping the benefits.
> 
> Especially if he/she is only interested in cleaning some critical part of the app and not the entire project.

Good point! I think you might have persuaded me to add the support for `--ignore-unclassified-modules` :-) If we do this, I think we should make it clear that this switch should be reserved only for special cases, and preferably used only temporarily. I believe that in most scenarios ignored boundaries should work better. IMO, it's best if nothing is ignored.

The switch probably won't be added in this PR, because I want to take a bit of time to think it through once more, while in the meantime I'd like to do a few other cleanups.

**Pull request merged**
